name: proj-openshift-chart

# Kubernetes namespace to install into (can be overridden)
namespace: nicolas-sierra-dev

replicaCount: 1


image:
  repository: jesusnicolassierra/proj-openshift-db
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "build-{{ tag }}"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "500m"
    memory: "800Mi"
  limits:
    cpu: "1000m"
    memory: "1500Mi"

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

configMap:
  enabled: true
  data:
    POSTGRES_DB: "proj-openshift"
    POSTGRES_HOST: "postgresql"
    POSTGRES_PORT: "5432"
    APP_PORT: "8080"

secret:
  enabled: true
  data:
    POSTGRES_USER: "openshift"
    POSTGRES_PASSWORD: "openshift"

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /q/health/live
    port: 8080
readinessProbe:
  httpGet:
    path: /q/health/ready
    port: 8080