name: microservicio-2

# Kubernetes namespace to install into (can be overridden)
namespace: nicolas-sierra-dev

replicaCount: 1

container:
  # Full image name without tag (e.g. 'adonispaz9506/hola-mundo-clase567')
  image: "jesusnicolassierra/proj-openshift-db"
  tag: "build-{{ tag }}"
  port: 8080

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: "500m"
    memory: "800Mi"
  limits:
    cpu: "1000m"
    memory: "1500Mi"

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

configMap:
  enabled: true
  data:
    POSTGRES_DB: "proj-openshift"
    POSTGRES_HOST: "postgres"
    POSTGRES_PORT: "5432"
    APP_PORT: "8080"

secret:
  enabled: true
  data:
    POSTGRES_USER: "openshift"
    POSTGRES_PASSWORD: "openshift"