name: CI-DockerBuild-db

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    uses: jnsierra/devops-pipelines/.github/workflows/docker-workflow.yml@main
    with:
      docker_image_name: proj-openshift-db
      name_project: proj-openshift-db     
    secrets: inherit